name: default_app_flutter
description: Default App Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.3
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.4 #ERRO
  #dio: 2.1.13 #Funciona
  #rxdart: 0.22.0 #Funciona
  #bloc_pattern: 2.2.3 #Funciona
  progress_dialog: ^1.2.0
  flutter_masked_text: ^0.8.0
  shared_preferences: ^0.5.3
  image_picker: ^0.6.4
  firebase_storage: ^3.0.3
  path_provider: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
